name: Trigger auto deployment for roundtable-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/roundtable-api-AutoDeployTrigger-32e23f05-5e02-4e17-a671-c51268b06684.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ROUNDTABLEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROUNDTABLEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROUNDTABLEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: roundtbleconreg.azurecr.io
          registryUsername: ${{ secrets.ROUNDTABLEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROUNDTABLEAPI_REGISTRY_PASSWORD }}
          containerAppName: roundtable-api
          resourceGroup: rg-roundtable
          imageToBuild: roundtbleconreg.azurecr.io/roundtable-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


